de:
#  houses: 'hause'
#  pages:
#  infos_a_z: 'informationen'
#  map: 'carte'
#  weather: 'wetter'

hu:
#  houses: 'hazak'
#  pages:
#  infos_a_z: 'informaciok'
#  map: 'terkep'
#  weather: 'idojaras'
